apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/hbence0408/myapp-backend:latest
        imagePullPolicy: Always
      imagePullSecrets:
      - name: ghcr-secret   # ← itt adjuk meg a secret nevét
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/hbence0408/myapp-frontend:latest
        imagePullPolicy: Always
      imagePullSecrets:
      - name: ghcr-secret   # ← ugyanaz a secret a frontendhez is
