# ===============================
# Backend Service
# ===============================
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080          # service port (belső)
      targetPort: 8080    # pod port
  type: ClusterIP        # csak klaszteren belül érhető el

---

# ===============================
# Frontend Service
# ===============================
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80            # service port (belső)
      targetPort: 80      # pod port
      nodePort: 30828     # fix NodePort kívülről való eléréshez
  type: NodePort          # kívülről is elérhető a Node IP + NodePort segítségével
